### ISSUE TITLE
MaxoutDens Import Error

### ISSUE THREAD

**Issue by akare55** [mravendi/AIclub#10]
Hello,
When I run the code, I take an error like below. How can I solve that?

ImportError: cannot import name 'MaxoutDense' from 'keras.layers.core' (/home/ubuntu/anaconda3/lib/python3.7/site-packages/keras/layers/core.py)

**Comment by mave5** [comment]
This could be due to the difference in Keras version. 
I am not sure what Keras version I used at the time. 
You either have to downgrade your Keras version to <v1.0 or try to update the layer based on the latest Keras version.
