### ISSUE TITLE
Train own dataset with Gans

### ISSUE THREAD

**Issue by reachsak** [mravendi/AIclub#11]
Hi , I've read about this project of yours ,  using GANs to generate images and annotations
"GAN_CMRI_32by32.ipynb"
I'd like know how can I train my own dataset with label at different size (say 512x512). I know it might be related to the npz file that use for training , I'd like to know how do your split and save your images and label into npz file. 
I'm new to Machine Learning here, i'd appreciate your help

**Comment by mave5** [comment]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html
