### ISSUE TITLE
trainfold1.npz

### ISSUE THREAD

**Issue by arnitkun** [mravendi/AIclub#8]
what is trainfold1.npz and where do I find it?

**Comment by mave5** [comment]
I added trainfold1.npz:
https://github.com/mravendi/gan/tree/master/data

However, it is better to download the dicom source from 
http://www.litislab.fr/?projet=1rvsc

and then convert them into your preferred python format.

**Comment by arnitkun** [comment]
can you tell me how to convert the DICOM format into numpy save?
I thought that the code actually used raw data which was stupid of me, I didn't realize it used npz.

**Comment by mave5** [comment]
you can use this lib to convert dicom to numpy:
http://dicom-numpy.readthedocs.io/en/latest/
